# Generated by Django 6.1 on 2026-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_resume_worker_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(choices=[('no_exp', 'Без опыта'), ('1-3', '1-3 года'), ('5+', 'Более 5 лет')], default='no_exp', max_length=50, verbose_name='Требуемый опыт'),
        ),
    ]
